### ISSUE TITLE
No possibility to close my connection to the server.

### ISSUE THREAD

**Issue by peychart** [area-of-dev/Nextcloud.AppImage#1]
Hi,
My old client (3.0.3) no longer works on ubuntu 22.04 update.
The latest version of the Nexcloud client no longer has a logout menu ... So I no longer know how to interrupt my connection when I’m away, my encrypted synchronized partition umounted.
Has this very useful possibility disappeared from the new versions or is it obtained in another way?...
Thanks

**Comment by AlexWoroschilow** [comment]
Hi there, 
that is  really unfortunate situation. 
I am afraid only the nextcloud developers can answer your question. 
Try this link: https://nextcloud.com/support/

**Comment by peychart** [comment]
Thank you very much for your answer.
Regards
